### PR TITLE
feat: add `remove` option field to playground

### PR DESCRIPTION
**Pull request by screensaversclub**
- Create new RegExp from user input 
- "global" and "ignore case" flags are exposed as checkboxes to user
- Tested with simple regex like `/[aeiou]/gi` (remove vowels) or `/(?<= )((a)|(an)|(the))(?= )/gi` (remove a/an/the with both positive and negative lookahead for space character)

### CODE REVIEW

**Comment by Trott** [comment]
Totally optional suggestion that you can feel free to ignore (or save for another PR), but the `remove` option is sort of an advanced option that very few (no?) users actually need, and that gets misunderstood/misused a lot, so it might not be a terrible idea to hide it in an element that needs to be expanded, maybe with something like this?:

```html
<details>
<summary>Advanced options</summary>
Remove: <input type="text">
</details>
```

**Comment by screensaversclub** [comment]
Happy to do so as I think you have a better idea how people tend to use the package. I'll push a commit with that. 

Do you think the charmap and multicharmap options would be folded into this advanced disclosure as well?

**Comment by Trott** [comment]
> Do you think the charmap and multicharmap options would be folded into this advanced disclosure as well?

I'd leave those out entirely. I can't even imagine a reliable way to implement them that isn't a UX nightmare.

**Comment by screensaversclub** [comment]
@Trott  circling back to this, do you think there's anything else you'd like to rethink about this PR here? (Not sure if it's pending my action. ) Thanks!

**Comment by Trott** [comment]
@screensaversclub Thanks for your patience. This looks good and I'll land it now.

**Pull request merged**
