### PR TITLE
add ة،ء missing Arabic characters

### PR DESCRIPTION
**Pull request by A-Tokyo**
- add ة،ء missing Arabic characters

Note: Thanks for the awesome work!

### CODE REVIEW

**Comment by Trott** [comment]
Thanks so much! Version 3.5.1 with this fix in it should be published to npm in a few minutes.

**Comment by A-Tokyo** [comment]
@Trott My duty! 💪 

There are a few arabic letters missing still,  I will issue a PR soon with all the missing characters, and a PR after it correcting a couple of letters when it comes to slugifying 💪

**Comment by Trott** [comment]
> There are a few arabic letters missing still, I will issue a PR soon with all the missing characters, and a PR after it correcting a couple of letters when it comes to slugifying 💪

Thanks! I'm ignorant about the Arabic alphabet and language and relied entirely on https://en.wikipedia.org/wiki/Romanization_of_Arabic and similar documents. With my ignorance, errors are not at all surprising. The lack of a one-to-one mapping for each letter and the various diacritics mean some choices were made (including, if I recall correctly, omitting _hamzah_ intentionally) that might have optimized for the wrong case. It would be great to have it all reviewed and corrected by someone who knows what they're doing!

**Comment by A-Tokyo** [comment]
Grateful for having the initial set done by you 💪 It just needs some optimizations. I will happily work on all of them ASAP

Yes I noticed the `hamza` topic, I will correct all the versions of the `aleph` character in an upcoming PR.

My strategy is:
- Add missing characters (non-breaking)
- Correct the slugifying of certain characters that are wrong atm. eg: the arabic word for `ibrahim` is slugified to `abrahim`, I will correct that as well but in a separate PR sine these are breaking.

And I am fluent in arabic so that should help :D expect my PRs soon 💪

**Pull request merged**
